---
sidebar: sidebar 
permalink: setup-email-upgrade-health-checker.html 
keywords: upgrade, health, checker 
summary: Você pode configurar e-mails para receber relatórios do Upgrade Health Checker. 
---
= Receba relatórios do Verificador de Saúde da Atualização por e-mail
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Upgrade Health Checker pode enviar relatórios diretamente para sua caixa de entrada. Habilite esse recurso por meio do arquivo config.yaml ou de um argumento de linha de comando. Quando habilitado, o Upgrade Health Checker envia os relatórios gerados (HTML, Excel ou JSON) para um ou mais destinatários por meio de um servidor SMTP. Quando desabilitado, nenhum relatório é enviado. Se a geração do relatório falhar e o envio de e-mails estiver habilitado, o Upgrade Health Checker envia os arquivos de log para os destinatários configurados.



[[configure-using-the-config-yaml-file]]
== Configurar usando o arquivo config.yaml

Você pode configurar as definições de e-mail no arquivo config.yaml, ativando os relatórios por e-mail, adicionando detalhes do servidor SMTP e especificando os endereços dos destinatários e os formatos dos relatórios.

. Ative o envio de relatórios por e-mail no arquivo config.yaml.
+
[listing]
----
# Email Report Configuration
EMAIL:
  ENABLED: true
----
. Adicione as configurações SMTP, os detalhes do remetente e o assunto:
+
[listing]
----
# SMTP Server Configuration
EMAIL:
  ENABLED: true
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [<port-number>]
----
. Adicione os endereços de e-mail dos destinatários e defina quais formatos de relatório o sistema enviará por e-mail, por exemplo, HTML, EXCEL, JSON ou ALL. Você também pode usar autenticação e criptografia:
+
[listing]
----
# Recipient Email Addresses, report formats
EMAIL:
  ENABLED: true
  TO: <recipient>
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  RECIPIENTS: "user1@example.com, user2@example.com"
  REPORT_FORMATS: "HTML,EXCEL,JSON"   # valid values: HTML, EXCEL, JSON or ALL
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
    USE_SMTP_AUTH: true
    USE_TLS: true
    USE_SSL: true
    USERNAME: "user@example.com"
    PASSWORD: "********"
----




[[configure-using-command-line-arguments]]
== Configurar usando argumentos de linha de comando

Você pode configurar as definições básicas de email usando argumentos de linha de comando para ativar relatórios, especificar destinatários e selecionar formatos de relatório.

. Ativar relatórios por e-mail usando argumentos de linha de comando:
+
[listing]
----
./uhc --email-enabled=true
----
. Forneça os endereços de e-mail dos destinatários:
+
[listing]
----
./uhc --email-recipients="user1@example.com, user2@example.com"
----
. Configure quais formatos de relatório são enviados por e-mail, por exemplo, HTML, EXCEL, JSON:
+
[listing]
----
./uhc --email-report-formats=HTML,EXCEL,JSON
----


[NOTE]
====
Você pode configurar os três atributos a seguir usando argumentos de linha de comando ou o arquivo config.yaml. Você pode configurar todos os demais atributos somente no arquivo config.yaml:

* E-mail ativado
* Destinatários de e-mail
* Formatos de relatório por e-mail


Observe que os argumentos da linha de comando substituem os valores do arquivo config.yaml.

Por exemplo:

[listing]
----
./uhc \
  --email-enabled=true
  --email-recipients="user1@example.com, user2@example.com" \
  --email-report-formats=HTML,EXCEL,JSON \
----
[listing]
----
EMAIL:
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----
====