---
sidebar: sidebar 
permalink: whats-new.html 
keywords: upgrade, health, checker, whats new, release, notes 
summary: Descubra as novidades neste site de documentação. 
---
= Novidades no Upgrade Health Checker
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre as novidades do Upgrade Health Checker (UHC). Você pode encontrar informações adicionais sobre melhorias acessando o bloco do Upgrade Health Checker no link:https://console.netapp.com/automationHub["Hub de Automação do NetApp Console"^] e visualizando os arquivos de download mais recentes do Upgrade Health Checker.



[[17-july-2026]]
== 17 de julho de 2026

Esta atualização adiciona diversas melhorias, incluindo um painel de visualização de risco da frota, suporte para autenticação e criptografia de e-mail, relatórios de contagem de unidades, suporte para versão recomendada do ONTAP e verificações de IMT para NAS e SAN.

* Painel de controle da UHC: visualização de *Risco da Frota* agora disponível
* Integração de e-mail: suporte para servidor de e-mail com autenticação e criptografia
* Adicionada a *Contagem de Unidades* no Resumo do Cluster no Relatório
* Agora a versão do ONTAP recomendada é suportada
* Adicionado suporte para verificações IMT em NAS e SAN




[[11-june-2026]]
== 11 de junho de 2026

Esta atualização adiciona a entrega de relatórios por e-mail, um parâmetro no painel para obter visões gerais rápidas do estado de saúde e novas seções de documentação para ajudar você a manter e solucionar problemas do Upgrade Health Checker.

* A UHC oferece suporte ao envio direto de relatórios para sua caixa de entrada.
+
link:setup-email-upgrade-health-checker.html["Receba relatórios do Verificador de Saúde da Atualização por e-mail"].

* Introduz o  `--dashboard`parâmetro que regenera o painel de controle a partir de execuções existentes em  `<runs>/dashboard/index.html`sem contatar um cluster. Fornece uma visão geral de alto nível do estado de integridade de todos os clusters que foram acessados recentemente.
+
link:dashboard-upgrade-health-checker.html["Painel de controle do verificador de integridade de upgrade"], link:upgrade-health-checker-input-parameters.html#dashboard["Parâmetro do dashboard"].

* Apresenta uma nova seção de Manutenção, Solução de Problemas e Perguntas Frequentes.
+
** Mantenha o Upgrade Health Checker em funcionamento verificando se há atualizações, monitorando os registros em busca de problemas recorrentes e certificando-se de que você configura a ferramenta corretamente.
+
link:maintain-upgrade-health-checker.html["Manter o verificador de integridade da atualização"].

** Solucione problemas comuns do Verificador de Integridade da Atualização e resolva erros que podem bloquear o planejamento da atualização do ONTAP.
+
link:troubleshoot-upgrade-health-checker.html["Solução de problemas do verificador de integridade da atualização"].

** Perguntas frequentes (FAQ) sobre o Upgrade Health Checker.
+
link:faq-upgrade-health-checker.html["Perguntas frequentes sobre o verificador de integridade da atualização"].







[[15-april-2026]]
== 15 de abril de 2026

Esta atualização adiciona um novo formato de relatório XLSX e requer acesso a um novo endpoint para que as atualizações automáticas funcionem.

* Você deve conceder acesso UHC a um novo endpoint (+https://api.activeiq.netapp.com+) para que os recursos de atualização automática funcionem.
+
link:set-up-upgrade-health-checker.html["Baixe e configure o Upgrade Health Checker"].

* A UHC agora oferece um novo formato de relatório (.XLSX - editável por humanos) que complementa os formatos HTML (legível por humanos) e JSON (legível por máquina).
+
link:generate-report-upgrade-health-checker.html["Gerar um relatório de atualização do ONTAP"].

+
link:automate-report-upgrade-health-checker.html["Automatize a geração de planos de atualização com o Upgrade Health Checker"].





[[13-february-2026]]
== 13 de fevereiro de 2026

O Upgrade Health Checker já está disponível. Esta ferramenta gera relatórios detalhados no local para ajudar você a concluir uma atualização do ONTAP com sucesso. Você pode usar o Upgrade Health Checker com estruturas de automação e orquestração existentes para economizar tempo ao atualizar clusters individuais ou múltiplos. O Upgrade Health Checker é compatível com atualizações para ONTAP 9.11.1 e versões posteriores.

link:learn-about-upgrade-health-checker.html["Saiba mais sobre o Upgrade Health Checker"].
